### ISSUE TITLE
Explaining the meaning of <where Java locates> and <where hadoop-2.6.0 locates>

### ISSUE THREAD

**Issue by 93T** [SabraO/Website-Content#3]
This is a small detail but I was wondering if it would be a good idea to explain <where Java locatse> and <where hadoop-2.6.0 locates> in step1 substep 3. Those values were intended to be changed (if I remember the process correctly, please correct me if I'm wrong) and that's not really explained or clear enough in the instructions.

**Comment by SabraO** [comment]
Those values were intended to be changed. Let me make it clearer in the tutorial.
