### ISSUE TITLE
Significance of Parallel Design section

### ISSUE THREAD

**Issue by 93T** [SabraO/Website-Content#4]
I was reading through this while checking grammar and I'm not understanding the purpose of the 'Parallel Design' section. It seems a bit random to the previous section but I think it's trying to tell me how to design k-means with this parallelism and centroids (center point) idea. I think this section could use some clarity. Especially on the opening line 'What are the model? What kind of data structure?'. Also, that first question'What are the model', is that suppose to be 'What are the models' or 'What is the model'?

**Comment by SabraO** [comment]
Related doc - https://dsc-spidal.github.io/harp/docs/examples/kmeans/
Related md file - https://github.com/SabraO/Website-Content/blob/master/examples/kmeans.md

**Comment by kyhhdm** [comment]
The structure of the documents under the section of "Example" all follow a same style, which is described in the opening "Overview". Therefore, in each of them, a section like 'Parallel Design' just jumps out suddenly. 
The technique contents, like the section of 'Parallel Design', may not be necessary for a user guide that tells people how to use the tool. IMO, it should be okay to remove those parts and make the content easy to understand. You can talk with Prof. Judy to make sure.

**Comment by SabraO** [comment]
I agree. For a user who is going to use the tool the design and implementation details are not necessary. This tutorial can be further divided into two sections which I will discuss with Prof. Judy.

For clarification, I have added the following sentence at the beginning of each tutorial.

"Before going through this tutorial take a look at the [overview](https://dsc-spidal.github.io/harp/docs/examples/overview/) section to get an understanding of the structure of the tutorial."
