### ISSUE TITLE
Clarity on parallel design function names?

### ISSUE THREAD

**Issue by 93T** [SabraO/Website-Content#5]
I was looking at this paragraph in the Parallel Design section of K-means and was confused by the names allreduce, regroup/allgather, push/pull, and reduce/broadcast. Are those function names? Here's the paragraph i was reading.

> For solution without model parallelism, Synchronize replicas of the model by allreduce, then calculate the new centroids and go to the next iteration. For vanilla kmeans, the combination of reduce/broadcast, push/pull, regroup/allgather are similar to allreduce.

If those are function names then I think it would be best to edit the paragraph like the following _(I will do this in my updates once I know for sure)_: 

> For a solution without model parallelism, Synchronize replicas of the model by `allreduce`, then calculate the new centroids and go to the next iteration. For vanilla k-means, the combination of `reduce/broadcast`, `push/pull`, `regroup/allgather` are similar to `allreduce`.

Also while I'm asking, for the names 'reduce/broadcast', 'push/pull', and 'regroup/allgather', are those two separate functions that work together or is that the name of one large function?

**Comment by kyhhdm** [comment]
yes, those are two separate functions that work in pair
